### ISSUE TITLE
problem with installing Jupyter matplotlob

### ISSUE THREAD

**Issue by fonzog** [pdeitel/IntroToPython#2]
Hello, when I enter "jupyter labextension install @jupyter-widgets/jupyterlab-manager" in the terminal on my mac, this is the response: "**An error occurred. ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website**". I tried to solve it, but nothing doesn't work. I'm new in this world, so pls help me. Thanks to everyone who will help me.

**Comment by pdeitel** [comment]
What platform are you using? Windows? macOS? Is that the only message or is there something more extensive?

**Comment by fonzog** [comment]
I’m using macOS. Yes this is the only message.

Inviato da iPhone

**Comment by pdeitel** [comment]
Please check if any of the recommendations in the following post help you: 
https://stackoverflow.com/questions/62325068/cannot-install-latest-nodejs-using-conda-on-mac
