### ISSUE TITLE
Errors about sys arguments

### ISSUE THREAD

**Issue by trombz** [pdeitel/IntroToPython#3]
Hello,

From the video course I typed everything as perfect as it is and no matter what framework I tried to run(Jupyter-notebook,from terminal(ipython),Colab(from google) and even also tried using Pycharm I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [72], in <cell line: 30>()
     27         axes.text(text_x, text_y, text, ha='center', va='bottom')
     29 # read command-line arguments for number of frames and rolls per frame
---> 30 number_of_frames = int(sys.argv[1])  
     31 rolls_per_frame = int(sys.argv[2])  
     33 sns.set_style('whitegrid')  # white backround with gray grid lines

ValueError: invalid literal for int() with base 10: '-f'

I just found your github now Paul and I also copied your code to my jupyter notebook and still got the same error message. What it does mean?

**Comment by pdeitel** [comment]
Hi @trombz, Please tell me specifically which example this is for? Which section of the book is it in. Thanks! Paul

**Comment by pdeitel** [comment]
I think what's going on here is that you're using the command-line arguments feature in Jupyter/Colab/PyCharm, but no arguments are being supplied. If you run the program as a script from the command-line, then you can pass in the required arguments. If you put the code in Jupyter/Colab/PyCharm, you would not use the sys.argv -- you'd just assign the values to variables.

**Comment by trombz** [comment]
> 

Hi Paul,

It's about ch06, [RollDieDynamic.py].

**Comment by pdeitel** [comment]
This script is meant to be executed from a .py file at the command line, not in a Python IDE, Jupyter or Colab. That's why you're getting the exception--there are no command-line arguments to convert to integers

**Comment by trombz** [comment]
> I think what's going on here is that you're using the command-line arguments feature in Jupyter/Colab/PyCharm, but no arguments are being supplied. If you run the program as a script from the command-line, then you can pass in the required arguments. If you put the code in Jupyter/Colab/PyCharm, you would not use the sys.argv -- you'd just assign the values to variables.

Thanks for the reply!Indeed it worked as soon as I tried to run from ipython!
