### ISSUE TITLE
Error on running RollDieDynamic.py // Not using Anaconda

### ISSUE THREAD

**Issue by LMeinhardt** [pdeitel/IntroToPython#4]
When trying to run it on iPython I get the following error:

File ["/Users/lmeinhardt/Programs/Python3/deitel/ch01/RollDieDynamic.py", line 17](coderunner:///Users/lmeinhardt/Programs/Python3/deitel/ch01/RollDieDynamic.py#(539,0)!), in update
    axes = sns.barplot(faces, frequencies, palette='bright')  # new bars
TypeError: barplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

![image](https://user-images.githubusercontent.com/31075973/195912390-12cb0227-bddb-45fe-bc5a-2b019419b0ae.png)

Note: Not using anaconda installation - using the standard installation from python.org - all libraries are installed and yet I get this error.

OS: MacOS 10.16
Python: Python 3.9.12

The content of the two parameters are:
Faces: [1, 2, 3, 4, 5, 6]
Frequencies: [0, 0, 0, 1, 0, 0]

**Comment by pdeitel** [comment]
Can you tell me what version of Seaborn is installed? Run this at the command line:

`conda list seaborn `

**Comment by LMeinhardt** [comment]
installed Seaborn-0.12.0 (installed through PIP)

**Comment by pdeitel** [comment]
Ok. The code as is works in 0.11.0.

I'll be looking at 0.12.0 over the weekend.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LMeinhardt** [comment]
Correct, it does run correctly on Seaborn 0.11. I only get the following warning regarding changes in the positional arguments coming on version 0.12 — hope this helps you:

/Users/XXX/Library/Python/3.9/lib/python/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(

Another 2 issues on your code:
- When you run the code, the number of rolls is always with one additional roll. _$ipython RollDieDynamic.py 50 1_ will result in 51 rolls, and 
- When you run _$ipython RollDieDynamic.py 50 **10**_ it multiplies the number_of_rolls by the rolls_per_frames+1 - see result below:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/31075973/195979271-c3ab45f8-c3db-40a8-9a9a-6c4c3627e1b2.png">
 
What I did to make it work 100% (with a very rookie correction - which is my current Python beginner level) was to change the following lines:
Line 33: _number_of_frames = int(sys.argv[1])_ **- 1**  
Line 44: _fargs=(**int((rolls_per_frame)/10)**, values, frequencies))_

Cheers

**Comment by pdeitel** [comment]
Turns out that the issue was the `sns.barplot` call. I thought I had corrected this a long time ago. The parameter names are required for the `faces` and `frequency` arguments.

`axes = sns.barplot(x=faces, y=frequencies, palette='bright')  # new bars`

With Seaborn 0.12.0, I get no warnings or errors after this update. 

Also, thanks for pointing out the off-by-one error.

**Comment by pdeitel** [comment]
code is updated in the repo for Chapter 1, 5 and 6.

**Comment by LMeinhardt** [comment]
You corrected the off-by-one error, but not the number of rolls... There were two errors.

**Comment by pdeitel** [comment]
That is correct as is. If you do 50 and 10 as arguments, it should produce 500 rolls.

**Comment by pdeitel** [comment]
The second argument is the # of rolls to process in the current frame. This allows you to more easily see the Law of Large Numbers in action by significantly increasing the rolls-per-frame.

**Comment by LMeinhardt** [comment]
Thanks for the fast confirmation... Cheers
