### ISSUE TITLE
New changes coming in Matplotlib 3.6

### ISSUE THREAD

**Issue by LMeinhardt** [pdeitel/IntroToPython#5]
Hello Paul,

I'm here just to provide you a new warning message I got when using Matplotlib - a DeprecationWarning to be more specific:

REF.: Chapter 6 - RollDieDynamic.py

- ~/Programs/Python3/deitel/ch06/RollDieDynamic.py:34: **MatplotlibDeprecationWarning**: The resize_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('resize_event', ResizeEvent(...)) instead.
-   _figure = plt.figure('Rolling a Six-Sided Die')  # Figure for animation_

- ~/Programs/Python3/deitel/ch06/RollDieDynamic.py:43: **MatplotlibDeprecationWarning**: The resize_event function was deprecated in Matplotlib 3.6 and will be removed two minor releases later. Use callbacks.process('resize_event', ResizeEvent(...)) instead.
-   _plt.show()  # display window_

**Comment by pdeitel** [comment]
I believe this was fixed by a more recent version of Matplotlib.
